config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :videos
  resources :lessons
  resources :pivot_tbls
  resources :courses
  resources :messages
  resources :roles


  # get  'welcome/index'
  # post 'messages/create'
  # post 'messages/new'


  devise_for :users
  scope "/admin" do
    resources :users
  end


  authenticated :user do
    root :to => 'courses#index', as: :authenticated_root
  end
  root :to => 'welcome#index'
  #root to: 'messages#index'
end

app/models/video.rb
class Video < ActiveRecord::Base
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:link, :title, :published_at, :likes, :dislikes, :uid)
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.datetime_select :published_at %>
  </div>
  <div class="field">
    <%= f.label :likes %><br>
    <%= f.number_field :likes %>
  </div>
  <div class="field">
    <%= f.label :dislikes %><br>
    <%= f.number_field :dislikes %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Videos</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Title</th>
      <th>Published at</th>
      <th>Likes</th>
      <th>Dislikes</th>
      <th>Uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.link %></td>
        <td><%= video.title %></td>
        <td><%= video.published_at %></td>
        <td><%= video.likes %></td>
        <td><%= video.dislikes %></td>
        <td><%= video.uid %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @video.link %>
</p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @video.published_at %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @video.likes %>
</p>

<p>
  <strong>Dislikes:</strong>
  <%= @video.dislikes %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @video.uid %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>