config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :videos
  resources :lessons
  resources :pivot_tbls
  resources :courses
  resources :messages
  resources :roles


  # get  'welcome/index'
  # post 'messages/create'
  # post 'messages/new'


  devise_for :users
  scope "/admin" do
    resources :users
  end


  authenticated :user do
    root :to => 'courses#index', as: :authenticated_root
  end
  root :to => 'welcome#index'
  #root to: 'messages#index'
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :course
  has_one :video
  has_many :messages

  def code
    returnValue = self.url.split('/').last if self.url
    return returnValue
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params[:lesson]
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lessons</h1>


<% if can? :create, Lesson %>
    <%= link_to 'Add Lesson', new_lesson_path %>
<% end %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= link_to 'Show', lesson %></td>
        <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
        <td><%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form' %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<div style="height: auto; width: 100%">
  <p id="notice"><%= notice %></p>

  <div class="list-group">
    <li class="list-group-item list-group-item-text">
      <strong>Name:</strong>
      <%= @lesson.topic %>
    </li>

    <li class="list-group-item list-group-item-text">
      <strong>URL:</strong>
      <%= @lesson.url %>
    </li>
  </div>
  <p>

  <div id=<%= "video"+@lesson.id.to_s %> class="media" style="float: left; height:600px; width: 50%">
    <strong>Video</strong><br>
    <iframe width="100%" height="400px" src="<%= @lesson.url %>" frameborder="0" allowfullscreen>

    </iframe>

<!-- <iframe width="560" height="315" src="https://www.youtube.com/embed/L9ArgxkC_Bc" frameborder="0" allowfullscreen></iframe>  -->
  </div>
  <div style="height: 600px; width: 45%; float: left; margin-left: 4%">
    <h1>Chat</h1>

    <ul id="chat" style="background-color: cornflowerblue; color: #F7F7F7; text-align: left; font-style: oblique; font-family: arial, sans-serif; font-size: medium">
      <%= if (defined?(@messages))
            @messages = Message.where(:lesson_id => @lesson.id)
            render(@messages)
          end %>
    </ul>

    <div>
      <%= form_for @message=Message.new, url: {action: "create", controller: "messages"}, remote: true do |f| %>
          <%= f.text_field :content %>
          <%= f.hidden_field :lesson_id, :value => @lesson.id %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
          <%= f.submit "Send" %>
      <% end %>
    </div>

    <%= subscribe_to "/messages/bla" %>
  </div>

  </p>

  <p>
    <strong>User:</strong>
    <%= @lesson.course %>
  </p>

  <%= link_to 'Edit', edit_lesson_path(@lesson) %> |
  <%= link_to 'Back', lessons_path %>
</div>

<!-- MSG DIALOG -->
<div id="msgModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" style="width: 40%;max-height: 80%">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="width:12px;">×</button>
        <h2 class="text-center">Messages</h2>
      </div>
      <div class="modal-body">

      </div>
    </div>
  </div>
</div>

<script type="text/javascript">

    $("document").ready(function () {
        var lesson_id = <%= @lesson.id %>; // for integer
        var data = <%= @messages=Message.where(:lesson_id => @lesson.id)
                raw @messages.to_json
            %>;


        createHistory(lesson_id, data)// this is your function in .js file
    });


</script>