config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :videos
  resources :lessons
  resources :pivot_tbls
  resources :courses
  resources :messages
  resources :roles


  # get  'welcome/index'
  # post 'messages/create'
  # post 'messages/new'


  devise_for :users
  scope "/admin" do
    resources :users
  end


  authenticated :user do
    root :to => 'courses#index', as: :authenticated_root
  end
  root :to => 'welcome#index'
  #root to: 'messages#index'
end

app/models/pivot_tbl.rb
class PivotTbl < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
end

app/controllers/pivot_tbls_controller.rb
class PivotTblsController < ApplicationController
  before_action :set_pivot_tbl, only: [:show, :edit, :update, :destroy]

  # GET /pivot_tbls
  # GET /pivot_tbls.json
  def index
    @pivot_tbls = PivotTbl.all
  end

  # GET /pivot_tbls/1
  # GET /pivot_tbls/1.json
  def show
  end

  # GET /pivot_tbls/new
  def new
    @pivot_tbl = PivotTbl.new
  end

  # GET /pivot_tbls/1/edit
  def edit
  end

  # POST /pivot_tbls
  # POST /pivot_tbls.json
  def create
    @pivot_tbl = PivotTbl.new(pivot_tbl_params)

    respond_to do |format|
      if @pivot_tbl.save
        format.html { redirect_to @pivot_tbl, notice: 'Pivot tbl was successfully created.' }
        format.json { render :show, status: :created, location: @pivot_tbl }
      else
        format.html { render :new }
        format.json { render json: @pivot_tbl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pivot_tbls/1
  # PATCH/PUT /pivot_tbls/1.json
  def update
    respond_to do |format|
      if @pivot_tbl.update(pivot_tbl_params)
        format.html { redirect_to @pivot_tbl, notice: 'Pivot tbl was successfully updated.' }
        format.json { render :show, status: :ok, location: @pivot_tbl }
      else
        format.html { render :edit }
        format.json { render json: @pivot_tbl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pivot_tbls/1
  # DELETE /pivot_tbls/1.json
  def destroy
    @pivot_tbl.destroy
    respond_to do |format|
      format.html { redirect_to pivot_tbls_url, notice: 'Pivot tbl was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pivot_tbl
      @pivot_tbl = PivotTbl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pivot_tbl_params
      params[:pivot_tbl]
    end
end

app/helpers/pivot_tbls_helper.rb
module PivotTblsHelper
end

app/views/pivot_tbls/_form.html.erb
<%= form_for(@pivot_tbl) do |f| %>
  <% if @pivot_tbl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pivot_tbl.errors.count, "error") %> prohibited this pivot_tbl from being saved:</h2>

      <ul>
      <% @pivot_tbl.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pivot_tbls/edit.html.erb
<h1>Editing Pivot Tbl</h1>

<%= render 'form' %>

<%= link_to 'Show', @pivot_tbl %> |
<%= link_to 'Back', pivot_tbls_path %>

app/views/pivot_tbls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pivot Tbls</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pivot_tbls.each do |pivot_tbl| %>
      <tr>
        <td><%= link_to 'Show', pivot_tbl %></td>
        <td><%= link_to 'Edit', edit_pivot_tbl_path(pivot_tbl) %></td>
        <td><%= link_to 'Destroy', pivot_tbl, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pivot tbl', new_pivot_tbl_path %>

app/views/pivot_tbls/new.html.erb
<h1>New Pivot Tbl</h1>

<%= render 'form' %>

<%= link_to 'Back', pivot_tbls_path %>

app/views/pivot_tbls/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pivot_tbl_path(@pivot_tbl) %> |
<%= link_to 'Back', pivot_tbls_path %>